language: julia

os:
  - linux

julia:
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

before_script:
  - julia -e 'using Pkg; Pkg.pin(PackageSpec(name="CxxWrap",version="0.8.1"))'
