# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
before_script:
  - julia -e 'using Pkg; Pkg.pin(PackageSpec(name="CxxWrap",version="0.8.1"))'
  - julia --project -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/JuliaFEM/Materials.jl"));
                          Pkg.build();
                          Pkg.test(; coverage=true)'
