name = "MFrontInterface"
uuid = "f46a0e2b-0ed0-5677-a4b9-4be52fead4dc"
authors = ["Tero Frondelius", "Thomas Helfer"]
version = "0.1.0"

[deps]
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
